### ISSUE TITLE
make it a filter

### ISSUE THREAD

**Issue by schriftgestalt** [joachimvu/ItalicExtremes#1]
Have you thought about making it a filter?

1) It would not use space in the sidebar. 
2) When assigned with a shortcut, you can invoke it very quickly and use it fully from the keyboard.
3) It could be used on export as an instance filter.

**Comment by joachimvu** [comment]
Good point, especially for the ability to be used on export, ex: for adding extreme points if one prefers to work with “slanted” nodes

How would you handle two actions each with their own options in a filter?

**Comment by joachimvu** [comment]
I’m thinking something like this?
<img width="515" alt="Capture d’écran 2020-05-20 à 1 30 38 AM" src="https://user-images.githubusercontent.com/1668442/82388350-b47b1500-9a39-11ea-99a9-ee0322b63ca6.png">

**Comment by schriftgestalt** [comment]
Looks good. Why did you close it?

**Comment by joachimvu** [comment]
Because it's done ;) sending a PR right now

Edit: I have an issue with using the filter as a custom parameter. I get:
`The filter “ItalicExtremes” was referenced in the custom parameters, but is not installed`
when trying to export a font with the filter. Any idea?

**Comment by schriftgestalt** [comment]
I send you a pull request

**Comment by joachimvu** [comment]
Cool!
The [doc](https://github.com/schriftgestalt/GlyphsSDK/tree/master/Python%20Templates/Filter%20with%20Dialog) for the filter plugin does put the UI in `settings()` (but it seems to be sample code from the Palette plugin, and I did some this way with no issues).
